unique_ids:
  assets:
    standard-page.html: IM4DA2BG2RSXJPEZ7YIZDYA7PJNW6BNZ
    theme.css: POWJTKBBBZUNHS7P76VJS5NMLSAGEC43
  forms:
    Form1: UWGNJBRBKURU6PAPYEFWI6GNOJNBVLD3
  modules: {}
  scripts: {}
  server_modules: {}
