unique_ids:
  assets:
    standard-page.html: IM4DA2BG2RSXJPEZ7YIZDYA7PJNW6BNZ
    theme.css: POWJTKBBBZUNHS7P76VJS5NMLSAGEC43
  forms:
    Homepage: UWGNJBRBKURU6PAPYEFWI6GNOJNBVLD3
    Hospitals: '1744905532945949097686372.7681'
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1744901782611418869703054.8929'
